### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by batuhan** [barbar/react-starter#1]

**Comment by batuhan** [comment]
Any suggestions @ilgooz?

**Comment by ilgooz** [comment]
we can save more on image size by running commands via single RUN command since each RUN commits a new layer on images. we also don't need to keep npm_modules after the build is done because webpack will be bundling all modules and our source code within a single js file for each server and client builds.
e.g.
`RUN npm install && npm run build && rm -rf node_modules`

**Comment by batuhan** [comment]
Right. Checkout #6
