### ISSUE TITLE
type safety

### ISSUE THREAD

**Issue by ilgooz** [barbar/react-starter#4]
I forgot to mention earlier that definition files for 3rd party modules can bypassed with plain <code>var request = require("require")</code> syntax in typescript. so I'd prefer typescript over flowtype due to it's flexibility, functionalities and large community. also, generated es5 code is much better than what babel transpiler produces

**Comment by batuhan** [comment]
I'm not familiar with TypeScript. Can we use import like ES6/ES7? And if used, does it bypass the definitions like your require example?

I think Barbar and @peergust should use the same technologies across the board. And since Peergust is utilises TypeScript, I think Barbar should too. My only concern is that I'm not familiar with it but that's not a very valid excuse.

Any thoughts, @altayaydemir?

**Comment by sevims** [comment]
Spot on. You just answered to your question by yourself. It's not a valid excuse, you need to learn TS in order to catch up with our base.

**Comment by ilgooz** [comment]
@batuhan yes typescript can do all what babel transpiler can. we don't necessarily need to bypass 3rd party module definition files(.ts, http://definitelytyped.org/tsd/ package manager for ts files) since it kills type safety while calling methods and etc. within that modules. it's better to use .ts when we can find one for that particular module. typescript also supports jsx syntax in es6 code so we should be good

**Comment by ilgooz** [comment]
btw here is a todomvc for react & typescript http://todomvc.com/examples/typescript-react/#/

**Comment by batuhan** [comment]
Hello TypeScript then.

I'm closing this.
